// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// disp_est_inCPP
double disp_est_inCPP(NumericVector pi_hat_emp);
RcppExport SEXP _unnamedDispersionMeasure_disp_est_inCPP(SEXP pi_hat_empSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pi_hat_emp(pi_hat_empSEXP);
    rcpp_result_gen = Rcpp::wrap(disp_est_inCPP(pi_hat_emp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_unnamedDispersionMeasure_disp_est_inCPP", (DL_FUNC) &_unnamedDispersionMeasure_disp_est_inCPP, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_unnamedDispersionMeasure(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
