# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

disp_est_inCPP <- function(pi_hat_emp) {
    .Call(`_unnamedDispersionMeasure_disp_est_inCPP`, pi_hat_emp)
}

